### ISSUE TITLE
Fix Wires Resize example

### ISSUE THREAD

**Issue by hasys** [ahome-it/lienzo-ks#15]
If you click on any button (Left | Right | Center | Top | Bottom) Circle in rectangle won't be aligned and you are not able to play with example shape any more.

Steps To Reproduce:
1. Open "Wires Resize" example in "Wires Examples" section
2. Click on any button in the example header, like (Left | Right | Center | Top | Bottom)
3. Try to resize or move the shape on canvas

Actual Result:
Inner circle is not aligned, you are not able to move example shape any more.

Expected Result:
Circle will be aligned, square is still re-sizable and movable.

**Comment by romartin** [comment]
Hey @hasys , if that's fine, feel free to close it. Thanks!

**Comment by hasys** [comment]
Hi @romartin, yes it is fixed now, thank you.
